**

!backend/
!backend/package.json
!backend/package-lock.json
!backend/tsconfig.json
!backend/src/
!backend/src/**

!packages/
!packages/game-engine/
!packages/game-engine/**

**/.env
**/.env.*
**/.env*
**/.npmrc
**/node_modules
**/node_modules/**
**/dist
**/dist/**
**/coverage
**/coverage/**
**/*.log
**/*.pem
**/*.key
**/*.crt
**/*.cer
**/*.p12
**/*.pfx
**/id_rsa*
**/id_ed25519*
**/keys
**/keys/**
**/certificates
**/certificates/**
